kind: Service
apiVersion: v1
metadata:
  name: kube-service
spec:
  type: NodePort
  selector:
    app: kube-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
  labels:
    app: kube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-deployment
      track: stable
  template:
    metadata:
      labels:
        app: kube-deployment
        track: stable
    spec:
      containers:
      - name: kube-addressbook
        image: erashish01/myaddressapp
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
